// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef aboutgui_hpp
#define aboutgui_hpp
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>

class FluidAboutWindow : public Fl_Window {
  void _FluidAboutWindow();
public:
  FluidAboutWindow(int X, int Y, int W, int H, const char *L = 0);
  FluidAboutWindow(int W, int H, const char *L = 0);
  FluidAboutWindow();
protected:
  Fl_Box *logoBox_;
};
#endif
